# syntax=docker/dockerfile:1
FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive ; apt update && apt install -y make wget git libtool pkg-config nano vim
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y openjdk-17-jdk-headless
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y libnotify-dev
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y faketime

RUN hostname
RUN domainname

