name: macos arm JNI Lib

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-macos-arm-nightly-artifact:
    name: Nightly Artifact macOS arm Build
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./ci_scripts/java_jni_lib_macos.sh

      - name: Rename artifact for nightly upload
        run: |
          pwd
          cp -v libjni_notifications.jnilib libjni_notifications_arm64.jnilib

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: libjni_notifications_arm64.jnilib
          path: libjni_notifications_arm64.jnilib
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "libjni_notifications_arm64.jnilib"


